#!/bin/bash
# Generate a docker-compose override file that explicitly maps all GPU device
# nodes and NVIDIA userspace libraries from the host into the container.
#
# This is a workaround for environments where `docker` is actually a Podman
# shim (crun runtime) and the external Docker Compose provider (v5.x) mangles
# the CDI device string `nvidia.com/gpu=all` into path-based `source:target`
# syntax, which Podman no longer recognizes as CDI. The `deploy.resources`
# GPU block is also silently ignored by this compose provider.
#
# Instead of relying on CDI resolution at compose time, this script reads the
# patched CDI spec (produced by scripts/gpu/fix_local_gpu_cdi.sh) and translates
# every deviceNode and mount entry into explicit compose `devices:` and
# `volumes:` entries. This achieves the same passthrough that
# `docker run --device nvidia.com/gpu=all` provides.
#
# Usage:
#   ./scripts/gpu/gen_gpu_compose_override.sh
#
# Output:
#   docker-compose.gpu.yml  (pass to compose via -f or COMPOSE_FILE)
#
# Recommended workflow:
#   ./scripts/gpu/fix_local_gpu_cdi.sh        # patch CDI spec (after reboot/driver update)
#   ./scripts/gpu/gen_gpu_compose_override.sh # generate override
#   docker compose -f docker-compose.yml -f docker-compose.gpu.yml up -d
#
# Or set in .env:
#   COMPOSE_FILE=docker-compose.yml:docker-compose.gpu.yml

set -euo pipefail

CDI_FILE="${CDI_FILE:-/var/run/cdi/nvidia.yaml}"
OUTPUT_FILE="${OUTPUT_FILE:-docker-compose.gpu.yml}"

if [ ! -f "$CDI_FILE" ]; then
    echo "[ERROR] CDI spec not found at $CDI_FILE" >&2
    echo "        Run ./scripts/gpu/fix_local_gpu_cdi.sh first." >&2
    exit 1
fi

if ! command -v python3 &>/dev/null; then
    echo "[ERROR] python3 is required to parse the CDI YAML spec." >&2
    exit 1
fi

echo "[INFO] Reading CDI spec from $CDI_FILE..."
echo "[INFO] Generating GPU compose override at $OUTPUT_FILE..."

python3 - "$CDI_FILE" "$OUTPUT_FILE" << 'PYEOF'
import sys
import yaml

cdi_path = sys.argv[1]
output_path = sys.argv[2]

with open(cdi_path) as f:
    spec = yaml.safe_load(f)

# The CDI spec structure is:
#   cdiVersion: 0.6.0
#   kind: nvidia.com/gpu
#   devices:
#     - name: all
#       containerEdits:
#         deviceNodes: [...]
#         mounts: [...]
#         env: [...]
#
# But nvidia-ctk may also put edits at the top-level containerEdits.
# We collect from both.

edits = {}

# Top-level containerEdits (some spec versions)
if 'containerEdits' in spec:
    for key in ('deviceNodes', 'mounts', 'env'):
        edits.setdefault(key, [])
        edits[key].extend(spec['containerEdits'].get(key, []))

# Per-device containerEdits (the 'all' device)
for dev in spec.get('devices', []):
    if dev.get('name') == 'all':
        ce = dev.get('containerEdits', {})
        for key in ('deviceNodes', 'mounts', 'env'):
            edits.setdefault(key, [])
            edits[key].extend(ce.get(key, []))

device_nodes = edits.get('deviceNodes', [])
mounts = edits.get('mounts', [])
envs = edits.get('env', [])

# Build compose override YAML
lines = []
lines.append("# Auto-generated by scripts/gpu/gen_gpu_compose_override.sh")
lines.append("# Do not edit manually - regenerate after driver/CDI updates.")
lines.append("#")
lines.append("# This file provides explicit GPU device + library passthrough for")
lines.append("# Podman/crun environments where CDI and deploy.resources are not")
lines.append("# resolved correctly by the external Docker Compose provider.")
lines.append("")
lines.append("services:")
lines.append("  comfy:")
lines.append("    devices:")

# Device nodes
for dn in device_nodes:
    host = dn.get('hostPath', dn.get('path', ''))
    container = dn.get('path', '')
    if host and container:
        lines.append(f"      - {host}:{container}")

# Also add /dev/nvidia0 and /dev/nvidia-caps if present on host but not in spec
# (some CDI specs omit nvidia0 when using MIG or cdi auto-detect quirks)
import os
extra_devs = ['/dev/nvidia0', '/dev/nvidia-caps']
existing_paths = {dn.get('path', '') for dn in device_nodes}
for ed in extra_devs:
    if os.path.exists(ed) and ed not in existing_paths:
        lines.append(f"      - {ed}:{ed}")

lines.append("    volumes:")

# Library mounts from CDI spec
for m in mounts:
    host = m.get('hostPath', '')
    container = m.get('containerPath', '')
    if host and container:
        # Check if host path exists; skip if not (avoids compose errors)
        if os.path.exists(host):
            lines.append(f"      - {host}:{container}:ro")
        else:
            print(f"  [WARN] Skipping missing host path: {host}", file=sys.stderr)

# NOTE: The CDI spec only mounts versioned .so files (e.g. libcuda.so.580.173.02),
# not the unversioned symlinks (libcuda.so.1, libcuda.so) that the dynamic
# linker resolves. These symlinks are created at container startup by the
# setup_nvidia_symlinks() function in entrypoint.sh, which scans for versioned
# .so files and creates the .so.<major> and .so symlinks, then runs ldconfig.

lines.append("    environment:")

# Env vars from CDI spec
for e in envs:
    if '=' in e:
        key = e.split('=')[0]
        # Override NVIDIA_VISIBLE_DEVICES to 'all' - the CDI spec sets it to
        # 'void' to prevent double-injection with the NVIDIA Container Toolkit
        # runtime, but we use crun (not nvidia runtime), so 'all' is correct.
        if key == 'NVIDIA_VISIBLE_DEVICES':
            lines.append(f"      - {key}=all")
        else:
            lines.append(f"      - {e}")

# Add NVIDIA_VISIBLE_DEVICES if not already present
env_keys = [e.split('=')[0] for e in envs if '=' in e]
if 'NVIDIA_VISIBLE_DEVICES' not in env_keys:
    lines.append("      - NVIDIA_VISIBLE_DEVICES=all")

with open(output_path, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"[INFO] Generated {len(device_nodes)} device nodes, {len(mounts)} mounts, {len(envs)} env vars")
PYEOF

echo "[SUCCESS] GPU compose override written to $OUTPUT_FILE"
echo ""
echo "To use it:"
echo "  docker compose -f docker-compose.yml -f $OUTPUT_FILE up -d"
echo ""
echo "Or add to .env:"
echo "  COMPOSE_FILE=docker-compose.yml:$OUTPUT_FILE"
